name: Build

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup install stable

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "./js/pnpm-lock.yaml"

      - name: Modify Version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed -e "s/^v//")
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          cd js
          npm version ${{ github.ref_name }}

      - name: Install dependencies
        working-directory: ./js
        run: pnpm install

      - name: Build JS
        working-directory: ./js
        run: |
          pnpm build:lib
          pnpm build:bin

      - name: Cache target
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Build Rust
        run: |
          cargo build --release

      - name: Publish JS
        working-directory: ./js
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare dlls
        run: |
          mkdir tmp
          cp target/release/usctool_cdylib.dll tmp/usctool.dll
          cp target/release/*.exe tmp
          cp target/usctool.h tmp

      - name: Push to build branch
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tmp/*
          tag_name: ${{ github.ref_name }}
